package com.bluetoothle

object Strings {
  const val state = "state"
  const val isEnabled = "isEnabled"
  const val isConnected = "isConnected"
  const val mtu = "mtu"
  const val error = "error"
  const val service = "service"
  const val characteristic = "characteristic"
  const val services = "services"
  const val isScanning = "isScanning"
  const val name = "name"
  const val address = "address"
  const val rssi = "rssi"
  const val connectionState = "connectionState"
  const val adapterState = "adapterState"
  const val value = "value"
  const val bytes = "bytes"
  const val uuid = "uuid"
  const val read = "read"
  const val write = "write"
  const val writeWithoutResponse = "writeWithoutResponse"
  const val notify = "notify"
  const val devices = "devices"
}
