package com.bluetoothle.types

enum class Error {
  DEVICE_NOT_FOUND,
  BLE_IS_OFF,
  SCAN_ERROR,
  GATT_ERROR,
  IS_NOT_CONNECTED,
  IS_ALREADY_SCANNING,
  IS_NOT_SCANNING,
  SERVICE_NOT_FOUND,
  CHARACTERISTIC_NOT_FOUND,
  TRANSACTION_ERROR,
  READ_ERROR,
  WRITE_ERROR,
  NOTIFICATIONS_ERROR,
  TIMEOUT
}
